### ISSUE TITLE
CI problems

### ISSUE THREAD

**Issue by realcr** [freedomlayer/offst#206]
There seems to be some problem with the CI process.
I think that things leak between different branches. Some observations:
- It seems like the badge for master reports an error that actually originates from PR https://github.com/freedomlayer/offst/pull/205, which was not yet merged.
- I think that I noticed test coverage results from some PR leak to the master badge before I merged that PR into master.

@pzmarzly : Do you have an idea what could the problem?
If you believe this is cache related (As mentioned earlier), I'm cool with removing the cache, at least for a while. I rather have slow CI over a wrong CI.

EDIT:

One example: When I currently enter: https://travis-ci.com/freedomlayer/offst (By clicking on the CI badge on master), I see the error from PR 205 written for branch master.

**Comment by pzmarzly** [comment]
To my understanding. badge for master reports that CI broke because of kcov issue. However, while image has `?branch=master`, it links to Travis "Current" tab, which shows the most recent build, not necessarily on master. This is weird design choice on Travis side, so I'm thinking about changing:

```markdown
[![Build Status](https://travis-ci.com/freedomlayer/offst.svg?branch=master)](https://travis-ci.com/freedomlayer/offst)
```

[![Build Status](https://travis-ci.com/freedomlayer/offst.svg?branch=master)](https://travis-ci.com/freedomlayer/offst)

to:

```markdown
[![Build Status](https://travis-ci.com/freedomlayer/offst.svg?branch=master)](https://travis-ci.com/freedomlayer/offst/branches)
```

[![Build Status](https://travis-ci.com/freedomlayer/offst.svg?branch=master)](https://travis-ci.com/freedomlayer/offst/branches)

So IMHO cache doesn't leak. It would be nice to fix kcov, though, so I can work on this.
